name: SafarSathi
description: "A trip tracking app by NATPAC."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.3

  # 🔹 Backend & API
  parse_server_sdk_flutter: ^9.0.0
  dio: ^5.4.2+1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  json_annotation: ^4.9.0

  # 🔹 UI & Styling
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4  # ✅ downgraded for http ^0.13.x compatibility
  animate_do: ^3.3.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

# 🔹 App Icon Config
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

# 🔹 Splash Screen Config
flutter_native_splash:
  color: "#000000"
  image: assets/icon/splash_screen.png
  android: true
  ios: true
  web: false

  android_12:
    image: assets/icon/splash_screen.png
    icon_background_color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
